version: '3.7'

services:
    currency-exchange:
        image: learningmicroservice/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
        deploy:
            resources:
                limits:
                    memory: 700M
        ports:
            - "8000:8000"
        networks: 
            - currency-network
        depends_on: 
            - naming-server
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

    currency-conversion:
        image: learningmicroservice/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
        deploy:
            resources:
                limits:
                    memory: 700M
        ports:
            - "8100:8100"
        networks: 
            - currency-network
        depends_on: 
            - naming-server
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    
    api-gateway:
        image: learningmicroservice/mmv2-api-gateway:0.0.1-SNAPSHOT
        deploy:
            resources:
                limits:
                    memory: 700M
        ports:
            - "8765:8765"
        networks: 
            - currency-network
        depends_on: 
            - naming-server
        environment: 
            EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

    naming-server:
        image: learningmicroservice/mmv2-naming-server:0.0.1-SNAPSHOT
        deploy:
            resources:
                limits:
                    memory: 700M
        ports:
            - "8761:8761"
        networks: 
            - currency-network

networks: 
    currency-network:
